# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodule',
            name='lung_orientation',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'LEFT'), (2, 'RIGHT')], default=0),
        ),
    ]
