# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_radiology_reporting_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-probability_concerning']},
        ),
    ]
