# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_candidate_review_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodulefeatures',
            name='case',
        ),
        migrations.AddField(
            model_name='nodule',
            name='appearance_feature',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'UNCHANGED'), (2, 'INCREASED'), (3, 'DECREASED'), (4, 'NEW')], null=True),
        ),
        migrations.AddField(
            model_name='nodule',
            name='density_feature',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'SOLID'), (2, 'SEMI SOLID'), (3, 'GROUND GLASS')], null=True),
        ),
        migrations.AddField(
            model_name='nodule',
            name='diameter',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='NoduleFeatures',
        ),
    ]
