# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20171210_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodule',
            old_name='appearance_feature',
            new_name='size_change',
        ),
    ]
