# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 22:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20180114_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodule',
            name='selected_area',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
