FROM ubuntu:18.04
USER root

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update

RUN apt-get install -y build-essential python3.6 python3.6-dev python3-pip python3.6-venv
RUN python3.6 -m pip install pip --upgrade

RUN apt-get install -y tcl tk python3.6-tk wget python-opencv python3-distutils git
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3.6 get-pip.py

# Default to Python 3.6
RUN rm /usr/bin/python
RUN ln -s /usr/bin/python3.6 /usr/bin/python

# Removing existing __pycache__ files
RUN find . -type d -name __pycache__ -exec rm -r {} \+

# Interface
COPY ./interface/requirements /requirements/interface
RUN pip install -U pip
RUN pip install -r /requirements/interface/local.txt

# Prediction
COPY ./prediction/.pylidcrc /root/.pylidcrc
COPY ./prediction/requirements/torch.txt /requirements/prediction/torch.txt
RUN pip install -r /requirements/prediction/torch.txt
COPY ./prediction/requirements/local.txt /requirements/prediction/local.txt
RUN pip install -r /requirements/prediction/local.txt
COPY ./prediction/requirements/base.txt /requirements/prediction/base.txt
RUN pip install -r /requirements/prediction/base.txt

# Documentation
COPY ./docs/requirements.txt /requirements/requirements.txt
RUN pip install -r /requirements/requirements.txt


WORKDIR /app
