FROM python:3.6
ENV PYTHONUNBUFFERED 1

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./prediction/requirements/local.txt /requirements/prediction/local.txt
RUN pip install -r /requirements/prediction/local.txt
COPY ./prediction/requirements/torch.txt /requirements/prediction/torch.txt
RUN pip install -r /requirements/prediction/torch.txt
COPY ./prediction/requirements/base.txt /requirements/prediction/base.txt
RUN pip install -r /requirements/prediction/base.txt

COPY ./interface/requirements /requirements/interface
RUN pip install -r /requirements/interface/local.txt

# Documentation
COPY ./docs/requirements.txt /requirements/requirements.txt
RUN pip install -r /requirements/requirements.txt

WORKDIR /app
