FROM python:3.6
ENV PYTHONUNBUFFERED 1

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./prediction/requirements /requirements/prediction
RUN pip install -r /requirements/prediction/local.txt

COPY ./interface/requirements /requirements/interface
RUN pip install -r /requirements/interface/local.txt

# Documentation
COPY ./docs/requirements.txt /requirements/requirements.txt
RUN pip install -r /requirements/requirements.txt

WORKDIR /app
