# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField(help_text='Voxel index for X axis, zero-index, from top left')),
                ('y', models.PositiveSmallIntegerField(help_text='Voxel index for Y axis, zero-index, from top left')),
                ('z', models.PositiveSmallIntegerField(help_text='Slice index for Z axis, zero-index')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(max_length=256)),
                ('uri', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='imagelocation',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.ImageSeries'),
        ),
    ]
