FROM node:8-slim

RUN apt-get update && apt-get install -y nginx bzip2 gettext-base

# get code
COPY ./interface/frontend /app

# install packages
RUN cd /app && npm install

# build application
RUN cd /app && npm run build

COPY ./compose/interface/nginx.conf.template /app/nginx.conf.template

COPY ./compose/interface/entrypoint-vue.sh /app

WORKDIR /app

RUN chmod +x entrypoint-vue.sh

ENTRYPOINT ["bash", "/app/entrypoint-vue.sh"]
