FROM python:3.6-jessie
ENV PYTHONUNBUFFERED 1

# Install Node
RUN curl --silent --location https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get install --yes nodejs

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./interface/requirements /requirements
RUN pip install -U pip && \
    pip install -r /requirements/local.txt

# Install Node dependencies
ADD ./interface/frontend/package.json /tmp/package.json
RUN cd /tmp && npm install

# Copy the scripts into the container
COPY ./compose/interface/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY ./compose/interface/start-dev.sh /start-dev.sh
RUN sed -i 's/\r//' /start-dev.sh
RUN chmod +x /start-dev.sh

WORKDIR /app

# Build the pages
RUN cd /app/frontend && \
    npm run build

ENTRYPOINT ["/entrypoint.sh"]
